# -*- coding: utf-8 -*-
"""gradio with HWDR
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1Bmt48XyhQxUOp2elWrMG4SIzX-HWCTme
"""


import numpy as np
import tensorflow as tf
import gradio as gr
import cv2

objects =  tf.keras.datasets.mnist
(training_images, training_labels), (test_images, test_labels) = objects.load_data()

training_images  = training_images / 255.0
test_images = test_images / 255.0

from tensorflow.keras.layers import Flatten, Dense
model = tf.keras.models.Sequential([Flatten(input_shape=(28,28)), 
                                    Dense(256, activation='relu'),
                                    Dense(256, activation='relu'),
                                    Dense(128, activation='relu'), 
                                    Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=10)

test=test_images[0].reshape(-1,28,28)
pred=model.predict(test)
print(pred)

def predict_image(img):
  cv2.imwrite('test.jpg',img)
  img_3d=img.reshape(-1,28,28)
  im_resize=img_3d/255.0
  prediction=model.predict(im_resize)
  pred=np.argmax(prediction)
  return pred

iface=gr.Interface(predict_image,inputs='sketchpad',outputs='label',capture_session=True).launch(share=True)




