# -*- coding: utf-8 -*-
"""yolo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G78Ni9MpTi4Zp37NFaCMHOiuspII-nX8
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip install -qr https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt  # install dependencies

from PIL import Image

import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images

# Inference
results = model(imgs)

# Results
results.print()
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0]  # img1 predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 1  433.50  433.50   517.5  714.5    0.687988     27     tie
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

def detect(image):
    results = model(image)  
    results.render() 
    return Image.fromarray(results.imgs[0])


import gradio as gr

gr.Interface(fn=detect, inputs=gr.inputs.Image(shape=None),outputs=gr.outputs.Image(type="auto", label=None)).launch(share=True,debug='True')